version: '3.5'

services:
  web:
    restart: always

    #build: .docker/web

    image: cyb10101/php-apache-dev:latest
    #image: cyb10101/php-apache-dev:7.2
    #image: cyb10101/php-apache-dev:7.1
    #image: cyb10101/php-apache-dev:7.0
    #image: cyb10101/php-apache-dev:5.6

    #image: cyb10101/php-nginx-dev:7.2
    #image: cyb10101/php-nginx-dev:7.1
    #image: cyb10101/php-nginx-dev:7.0
    #image: cyb10101/php-nginx-dev:5.6

    #image: webdevops/php-apache-dev:7.2
    #image: webdevops/php-apache-dev:7.1
    #image: webdevops/php-apache-dev:7.0
    #image: webdevops/php-apache-dev:5.6

    #image: webdevops/php-nginx-dev:7.2
    #image: webdevops/php-nginx-dev:7.1
    #image: webdevops/php-nginx-dev:7.0
    #image: webdevops/php-nginx-dev:5.6

    volumes:
      - .:/app
      - ~/.ssh:/home/application/.ssh
      - ~/.composer/cache:/home/application/.composer/cache
      - ~/.gitconfig:/home/application/.gitconfig

    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=~^(.+\.)?docker-website\.(vm|vm\d+\.example\.org)$$
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISMOD=ioncube
      - PHP_SENDMAIL_PATH="/home/application/go/bin/mhsendmail --smtp-addr=global-mail:1025"
      - XDEBUG_REMOTE_HOST=192.168.178.123
      - XDEBUG_REMOTE_PORT=9000
      - php.xdebug.idekey=PHPSTORM
      - php.xdebug.remote_log=/app/xdebug.log
      - php.display_errors=1
    working_dir: /app

networks:
  default:
    external:
      name: global
